aiortc/aioice

- aioice/compat.py
* the CompatSecrets.choice method is used by random_string to generate tokens some of which probably should come from a cryptographically secure random number generator, the previous use of random.choice did not fulfil this requirement.
* I looked at the CPython source code, and [at least since 2010 `random.SystemRandom`](https://github.com/python/cpython/blob/c585eecfb0384a9c6b560477c1f04c43b55cc8e3/Lib/random.py#L617) is a class derived from `random.Random` that only overwrites the actual methods retrieving the randomness by calls to urandom, so SystemRandom.choice will be available on any remotely recent CPython version, if it has support for `os.urandom`.
> Fix potential vulnerability in comapt.secrets

- aioice/ice.py
I ran into an issue where I'd exceed the stack depth if I opened a data-only connection from a web client and then leave the page (e.g. by refreshing it.)  This patch represents my attempt to solve the problem.
I still haven't discovered how to catch disconnections, but at least with this patch I don't get double-faults once the connection times out.
> ice: prevent infinite loop on unclean shutdown

- src/aioice/ice.py
Until #14 is fixed, aioice doesn't work with Chrome until STUN candidates come through, because it doesn't get a valid IP from the initial set of candidates. However, thanks to `_early_checks`, it does work in ICE-CONTROLLING mode, as long as `request_received` is called before `_connect`. In practice, this means the `cli.py offer` copy/paste example works, but none of the others do unless you add `asyncio.sleep(1)` before `pc.setRemoteDescription`.
To make it clear that the candidates are being rejected, this PR logs out instead of silently swallowing an invalid candidate.
As a secondary thing, I can't tell whether the `_early_checks` behaviour is correct. I don't know whether ICE should work with no candidates (Chrome doesn't even try to connect if there are no channels on a …
> Don't silently swallow invalid candidate exception

- src/aioice/ice.py
- tests/test_ice.py
Since Python 3.8, we need to wrap coroutines in a task before passing
them to asyncio.wait().
Until Python 3.6 support is dropped we cannot use asyncio.create_task(),
so use the less readable asyncio.ensure_future().
> Use modern asyncio.wait() syntax to avoid deprecation warning

- docs/changelog.rst
- docs/index.rst
- examples/ice-client.py
- src/aioice/ice.py
- tests/test_ice.py
- tests/test_ice_trickle.py
- tests/utils.py
Also remove the deprecated `remote_candidates` setter.
> [breaking] make add_remote_candidate a coroutine

- docs/changelog.rst
- src/aioice/turn.py
We must not assume the server accepted the LIFETIME requested by the
client for the allocation, use the actual value returned by the server.
> [turn] honour the LIFETIME returned by the server

- docs/changelog.rst
- src/aioice/turn.py
- tests/test_turn.py
Channel bindings expire after 600s. As our TURN implementation is used
with ICE (which uses consent queries), we will frequently send out data.
We take this opportunity to refresh the channel bindings as needed.
> [turn] periodically refresh channel binding (fixes: #29)

- setup.py
dnspython version 2.0.0 is the first one implementing QueryMessage on dns Message : see https://dnspython.readthedocs.io/en/stable/whatsnew.html#id2
Without it, aiortc crash with some exception:
````
Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
self._context.run(self._callback, *self._args)
File "/usr/lib/python3.8/asyncio/selector_events.py", line 1019, in _read_ready
self._protocol.datagram_received(data, addr)
File "/usr/local/lib/python3.8/dist-packages/aioice/mdns.py", line 55, in datagram_received
if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute …
```
> [mdns]: require dnspython >= 2.0.0

- src/aioice/ice.py
It could happen that the local candidate is not set when we enter `connection_lost`:
```
Traceback (most recent call last):                                                                  
File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run                                     
self._context.run(self._callback, *self._args)                                                  
File "/usr/lib/python3.9/asyncio/selector_events.py", line 736, in _call_connection_lost          
self._protocol.connection_lost(exc)                                                             
File "/home/ivan/venv-3.9/lib/python3.9/site-packages/aioice/ice.py", line 173, in connection_lost
self.receiver.data_received(None, self.local_candidate.component)                               
AttributeError: …
```
> [ice] connection_lost: local candidate may not have been set

- src/aioice/ice.py
- src/aioice/turn.py
Hi.
The aiortc receiver will have packet loss if it receives a large amount of media data in a short time. After looking up the webrtc native code, I find this setting.
https://chromium.googlesource.com/external/webrtc/+/06b8f7ea326af3c554755048b10e3e422f019ffa/media/base/media_constants.cc#19
```cpp
const int kVideoRtpRecvBufferSize = 262144;
```
https://chromium.googlesource.com/external/webrtc/+/06b8f7ea326af3c554755048b10e3e422f019ffa/media/engine/webrtc_video_engine.cc#1895
```cpp
int recv_buffer_size = kVideoRtpRecvBufferSize;
if (!group_name_recv_buf_size.empty() &&
(sscanf(group_name_recv_buf_size.c_str(), "%d", &recv_buffer_size) != 1 ||
recv_buffer_size <= 0)) {
RTC_LOG(LS_WARNING) << "Invalid receive buffer size: "
<< group_name_recv_buf_size;
recv_buffer_size = …
```
> Set the RTP recv/send buffer to a bigger size.

- tests/test_turn.py
- tests/turnserver.py
If no `protocol` argument is passed to the `ssl.SSLContext()` constructor, it defaults to `ssl.PROTOCOL_TLS` which is deprecated since Python 3.10.
Explicitly use `ssl.PROTOCOL_TLS_CLIENT` or `ssl.PROTOCOL_TLS_SERVER` to fix the depreaction warning as these constants have been available since Python 3.6.
> [tests] fix ssl deprecation warnings

- src/aioice/stun.py
- src/aioice/turn.py
- tests/test_turn.py
- tests/turnserver.py
Makes turn/tcp work.
This fixed `x DTLS receive timeout` that has been reported in some issues.
Probably related:
https://github.com/aiortc/aiortc/issues/413
https://github.com/aiortc/aiortc/issues/593
https://github.com/aiortc/aiortc/issues/400
> TCP requires padding to multiple of 4 bytes (RFC 8656 12.5)

- src/aioice/__init__.py
- src/aioice/ice.py
- tests/test_ice.py
Much like `iceTransportPolicy` in the [RTCPeerConnection configuration](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection). For example useful when testing STUN/TURN in a network where host candidates would otherwise be used.
> Optionally force gathering of only relay (STUN/TURN) candidates.

- setup.py
- src/aioice/ice.py
- src/aioice/mdns.py
- tests/test_ice.py
The `netifaces` package is no longer maintained, so no new wheels are being published. As it is not a pure Python package, this means that installing `aioice` would require users to compile `netifaces` themselves which is not trivial on some platforms.
We use the `ifaddr` package instead, which is a pure Python package.
> Switch from `netifaces` to `ifaddr` (fixes: #62)

- src/aioice/ice.py
I get errors from static type checkers when I pass None to signal the end of candidates. I would appreciate if this fix is merged to avoid adding unnecessary `# type: ignore` comments to the code
> Fixed annotation for add_remote_candidate() to allow None

- src/aioice/ice.py
- tests/test_ice.py
and enforce the length according to
https://datatracker.ietf.org/doc/html/rfc5245#section-15.1
This allows implementing the peerconnection with a single set of local credentials in
https://github.com/aiortc/aiortc/pull/1229
> Allow creating a connection with ufrag and pwd

- .github/workflows/tests.yml
Without a token we are getting rate-limited, resulting in an incomplete coverage report.
> Update GitHub actions, use a token to upload coverage

- src/aioice/stun.py
- tests/test_stun.py
When decoding a XOR-MAPPED-ADDRESS we must first check the address's length is correct for the protocol family before applying XOR. Otherwise we may attempt to XOR data which is too long, resulting in an `IndexError`.
Fixes: #79
> Harden decoding of XOR-MAPPED-ADDRESS

- src/aioice/stun.py
nit: looks like this `print` is not intended to be in the code?
> Delete print() in stun.py

- pyproject.toml
> Adjust linter configuration to prevent `print()` usage
